import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Button from "@/shared/ui/Button/Button";
import Header from "@/widgets/Header";
import NewFilmsSlider from "@/widgets/NewFilmsSlider/NewFilmsSlider.jsx";
import TopFilmsSlider from "@/widgets/TopFilmsSlider/TopFilmsSlider.jsx";
import TopSeriesSlider from "@/widgets/TopSeriesSlider/TopSeriesSlider.jsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.background}>
        <Header></Header>
        <NewFilmsSlider></NewFilmsSlider>
        <TopFilmsSlider></TopFilmsSlider>
        <TopSeriesSlider></TopSeriesSlider>
      </main>
    </>
  );
}
